# Generated by Django 2.2 on 2019-10-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactphone',
            name='service',
            field=models.IntegerField(choices=[(1, 'iMessage'), (2, 'SMS')], default=2),
        ),
    ]
