# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('send_at', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=160)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactPhone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
