# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('messaging', '0002_auto_20191005_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(max_length=160)),
                ('members', models.ManyToManyField(to='contacts.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
