# Generated by Django 2.2 on 2019-10-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_distributionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='distribution_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.DistributionList'),
        ),
    ]
