# Generated by Django 2.2 on 2019-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_distribution_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlist',
            name='members',
            field=models.ManyToManyField(to='contacts.ContactPhone'),
        ),
    ]
