# Generated by Django 2.2 on 2019-10-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20191006_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='distribution_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.DistributionList'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ClientPhone'),
        ),
    ]
